import {
  TeacherProfile,
  TurmaClass,
  AttendanceSession,
  ClassGradeBook,
  ClassEvaluation,
  NotificationItem,
  TeacherAvailabilitySubmission,
  ClassMaterial,
  TimetableSlot,
  AcademicCalendarEvent,
} from './types';

export const INITIAL_TEACHER_PROFILE: TeacherProfile = {
  id: 'prof-01',
  name: 'Prof. Dr. Marcelo Carvalho Silveira',
  titulacao: 'Doutor em Ciência da Computação (USP)',
  matricula: 'PF-20184920',
  email: 'marcelo.silveira@universidade.edu.br',
  phone: '(11) 98765-4321',
  department: 'Departamento de Computação e Tecnologia da Informação (DCTI)',
  officeRoom: 'Gabinete 304 - Bloco Tecnológico',
  officeHours: 'Segundas e Quartas das 17:30 às 18:45 | Sextas das 14:00 às 16:00',
  bio: 'Docente Permanente com 12 anos de experiência acadêmica e industrial. Pesquisador nas áreas de Engenharia de Software Orientada a Domínio, Inteligência Artificial Aplicada e Arquitetura de Sistemas Distribuídos.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  weeklyWorkloadHours: 24,
  admissionYear: 2018,
  lattesUrl: 'http://lattes.cnpq.br/1234567890123456',
};

const STUDENTS_ENG: any[] = [
  { id: 'st-01', name: 'Ana Carolina Mendes', matricula: '20241011', email: 'ana.mendes@aluno.edu.br', currentAttendancePercent: 94 },
  { id: 'st-02', name: 'Bruno Henrique Souza', matricula: '20241012', email: 'bruno.souza@aluno.edu.br', currentAttendancePercent: 88 },
  { id: 'st-03', name: 'Camila Fernandes Lima', matricula: '20241013', email: 'camila.lima@aluno.edu.br', currentAttendancePercent: 100 },
  { id: 'st-04', name: 'Daniel Augusto Ramos', matricula: '20241014', email: 'daniel.ramos@aluno.edu.br', currentAttendancePercent: 72 },
  { id: 'st-05', name: 'Eduarda Vasconcelos', matricula: '20241015', email: 'eduarda.v@aluno.edu.br', currentAttendancePercent: 96 },
  { id: 'st-06', name: 'Felipe Matheus Costa', matricula: '20241016', email: 'felipe.costa@aluno.edu.br', currentAttendancePercent: 85 },
  { id: 'st-07', name: 'Gabriela Duarte Prado', matricula: '20241017', email: 'gabriela.prado@aluno.edu.br', currentAttendancePercent: 92 },
  { id: 'st-08', name: 'Guilherme Toledo Nogueira', matricula: '20241018', email: 'guilherme.nogueira@aluno.edu.br', currentAttendancePercent: 78 },
  { id: 'st-09', name: 'Helena Pires Albuquerque', matricula: '20241019', email: 'helena.albuquerque@aluno.edu.br', currentAttendancePercent: 96 },
  { id: 'st-10', name: 'Igor Vinicius Siqueira', matricula: '20241020', email: 'igor.siqueira@aluno.edu.br', currentAttendancePercent: 68 },
  { id: 'st-11', name: 'Juliana Beatriz Santos', matricula: '20241021', email: 'juliana.santos@aluno.edu.br', currentAttendancePercent: 90 },
  { id: 'st-12', name: 'Lucas Gabriel Moreira', matricula: '20241022', email: 'lucas.moreira@aluno.edu.br', currentAttendancePercent: 94 },
  { id: 'st-13', name: 'Mariana Castro Ribeiro', matricula: '20241023', email: 'mariana.ribeiro@aluno.edu.br', currentAttendancePercent: 88 },
  { id: 'st-14', name: 'Pedro Henrique Antunes', matricula: '20241024', email: 'pedro.antunes@aluno.edu.br', currentAttendancePercent: 92 },
  { id: 'st-15', name: 'Renata Lemos Guimarães', matricula: '20241025', email: 'renata.lemos@aluno.edu.br', currentAttendancePercent: 96 },
];

const STUDENTS_ALG: any[] = [
  { id: 'st-21', name: 'Alexandre Borges', matricula: '20251001', email: 'alexandre.b@aluno.edu.br', currentAttendancePercent: 95 },
  { id: 'st-22', name: 'Beatriz Rezende Silva', matricula: '20251002', email: 'beatriz.rezende@aluno.edu.br', currentAttendancePercent: 92 },
  { id: 'st-23', name: 'Carlos Eduardo Meireles', matricula: '20251003', email: 'carlos.meireles@aluno.edu.br', currentAttendancePercent: 86 },
  { id: 'st-24', name: 'Debora Cristina Teles', matricula: '20251004', email: 'debora.teles@aluno.edu.br', currentAttendancePercent: 74 },
  { id: 'st-25', name: 'Enzo Gabriel Tavares', matricula: '20251005', email: 'enzo.tavares@aluno.edu.br', currentAttendancePercent: 90 },
  { id: 'st-26', name: 'Fernanda Paiva Rocha', matricula: '20251006', email: 'fernanda.rocha@aluno.edu.br', currentAttendancePercent: 98 },
  { id: 'st-27', name: 'Gustavo Martins', matricula: '20251007', email: 'gustavo.m@aluno.edu.br', currentAttendancePercent: 88 },
  { id: 'st-28', name: 'Isabela Monteiro', matricula: '20251008', email: 'isabela.m@aluno.edu.br', currentAttendancePercent: 94 },
  { id: 'st-29', name: 'Joao Vitor Carvalho', matricula: '20251009', email: 'joao.carvalho@aluno.edu.br', currentAttendancePercent: 82 },
  { id: 'st-30', name: 'Larissa Moura Farias', matricula: '20251010', email: 'larissa.moura@aluno.edu.br', currentAttendancePercent: 96 },
];

const STUDENTS_BD: any[] = [
  { id: 'st-31', name: 'Arthur Alcantara', matricula: '20231011', email: 'arthur.a@aluno.edu.br', currentAttendancePercent: 92 },
  { id: 'st-32', name: 'Bianca Macedo', matricula: '20231012', email: 'bianca.m@aluno.edu.br', currentAttendancePercent: 90 },
  { id: 'st-33', name: 'Caio Junqueira', matricula: '20231013', email: 'caio.j@aluno.edu.br', currentAttendancePercent: 85 },
  { id: 'st-34', name: 'Daniela Fontes', matricula: '20231014', email: 'daniela.f@aluno.edu.br', currentAttendancePercent: 97 },
  { id: 'st-35', name: 'Erick Nobrega', matricula: '20231015', email: 'erick.n@aluno.edu.br', currentAttendancePercent: 79 },
  { id: 'st-36', name: 'Flavia Campos', matricula: '20231016', email: 'flavia.c@aluno.edu.br', currentAttendancePercent: 91 },
  { id: 'st-37', name: 'Gabriel Santana', matricula: '20231017', email: 'gabriel.s@aluno.edu.br', currentAttendancePercent: 94 },
  { id: 'st-38', name: 'Heitor Fagundes', matricula: '20231018', email: 'heitor.f@aluno.edu.br', currentAttendancePercent: 88 },
];

const STUDENTS_IA: any[] = [
  { id: 'st-41', name: 'Alice Bittencourt', matricula: '20221001', email: 'alice.b@aluno.edu.br', currentAttendancePercent: 100 },
  { id: 'st-42', name: 'Bernardo Castilho', matricula: '20221002', email: 'bernardo.c@aluno.edu.br', currentAttendancePercent: 95 },
  { id: 'st-43', name: 'Clarice Machado', matricula: '20221003', email: 'clarice.m@aluno.edu.br', currentAttendancePercent: 92 },
  { id: 'st-44', name: 'Diego Valadares', matricula: '20221004', email: 'diego.v@aluno.edu.br', currentAttendancePercent: 88 },
  { id: 'st-45', name: 'Eloisa Gouveia', matricula: '20221005', email: 'eloisa.g@aluno.edu.br', currentAttendancePercent: 96 },
  { id: 'st-46', name: 'Fernando Bastos', matricula: '20221006', email: 'fernando.b@aluno.edu.br', currentAttendancePercent: 90 },
];

export const INITIAL_CLASSES: TurmaClass[] = [
  {
    id: 'turma-eng301',
    code: 'ENG-301',
    name: 'Engenharia de Software',
    course: 'Bacharelado em Ciência da Computação',
    semester: '2026/1 - 5º Semestre',
    period: 'Noturno',
    room: 'Laboratório 402 - Bloco B',
    workloadHours: 80,
    studentsCount: STUDENTS_ENG.length,
    scheduleDescription: 'Terças e Quintas: 18:50 às 20:30',
    color: '#3b82f6', // blue
    syllabus: 'Ciclos de vida de software, Metodologias Ágeis (Scrum/Kanban), Engenharia de Requisitos, Modelagem UML, Padrões de Projeto (GoF), Arquitetura Hexagonal e Clean Architecture, Testes de Software e CI/CD.',
    students: STUDENTS_ENG,
  },
  {
    id: 'turma-alg202',
    code: 'ALG-202',
    name: 'Algoritmos e Estruturas de Dados II',
    course: 'Engenharia de Software & Ciência da Computação',
    semester: '2026/1 - 3º Semestre',
    period: 'Matutino',
    room: 'Sala 204 - Bloco Central',
    workloadHours: 80,
    studentsCount: STUDENTS_ALG.length,
    scheduleDescription: 'Segundas e Quartas: 07:30 às 09:10',
    color: '#10b981', // emerald
    syllabus: 'Árvores Binárias de Busca, Árvores AVL e Rubro-Negras, Tabelas Hash, Grafos (Busca em Largura, Profundidade, Dijkstra, Kruskal), Algoritmos Gulosos e Programação Dinâmica.',
    students: STUDENTS_ALG,
  },
  {
    id: 'turma-bd401',
    code: 'BD-401',
    name: 'Banco de Dados Avançado',
    course: 'Bacharelado em Sistemas de Informação',
    semester: '2026/1 - 7º Semestre',
    period: 'Noturno',
    room: 'Laboratório 201 - Bloco A',
    workloadHours: 60,
    studentsCount: STUDENTS_BD.length,
    scheduleDescription: 'Quartas: 20:45 às 22:25 | Sextas: 18:50 às 20:30',
    color: '#8b5cf6', // purple
    syllabus: 'Processamento e Otimização de Consultas SQL, Controle de Concorrência e Transações ACID, Bancos NoSQL (Documento, Chave-Valor, Grafos), Sharding e Replicação, Indexação Avançada.',
    students: STUDENTS_BD,
  },
  {
    id: 'turma-ia501',
    code: 'IA-501',
    name: 'Inteligência Artificial Aplicada',
    course: 'Bacharelado em Ciência da Computação',
    semester: '2026/1 - 9º Semestre',
    period: 'Vespertino',
    room: 'Auditório 3 - Prédio de Pós-Graduação',
    workloadHours: 60,
    studentsCount: STUDENTS_IA.length,
    scheduleDescription: 'Sextas: 13:30 às 17:10 (Bloco Duplo)',
    color: '#f59e0b', // amber
    syllabus: 'Fundamentos de Machine Learning, Redes Neurais Artificiais, Deep Learning, Processamento de Linguagem Natural, Large Language Models e Ética em Inteligência Artificial.',
    students: STUDENTS_IA,
  },
];

export const INITIAL_ATTENDANCE: AttendanceSession[] = [
  {
    id: 'att-01',
    classId: 'turma-eng301',
    date: '2026-08-18',
    lessonNumber: 1,
    subjectTopic: 'Introdução aos Padrões de Criação (Factory Method & Builder)',
    createdAt: '2026-08-18T19:00:00Z',
    records: [
      { studentId: 'st-01', status: 'presente' },
      { studentId: 'st-02', status: 'presente' },
      { studentId: 'st-03', status: 'presente' },
      { studentId: 'st-04', status: 'ausente', notes: 'Sem justificativa' },
      { studentId: 'st-05', status: 'presente' },
      { studentId: 'st-06', status: 'presente' },
      { studentId: 'st-07', status: 'presente' },
      { studentId: 'st-08', status: 'ausente' },
      { studentId: 'st-09', status: 'presente' },
      { studentId: 'st-10', status: 'justificada', notes: 'Atestado médico entregue' },
      { studentId: 'st-11', status: 'presente' },
      { studentId: 'st-12', status: 'presente' },
      { studentId: 'st-13', status: 'presente' },
      { studentId: 'st-14', status: 'presente' },
      { studentId: 'st-15', status: 'presente' },
    ],
  },
  {
    id: 'att-02',
    classId: 'turma-eng301',
    date: '2026-08-13',
    lessonNumber: 2,
    subjectTopic: 'Clean Architecture e Inversão de Dependências na Prática',
    createdAt: '2026-08-13T19:00:00Z',
    records: [
      { studentId: 'st-01', status: 'presente' },
      { studentId: 'st-02', status: 'presente' },
      { studentId: 'st-03', status: 'presente' },
      { studentId: 'st-04', status: 'ausente' },
      { studentId: 'st-05', status: 'presente' },
      { studentId: 'st-06', status: 'presente' },
      { studentId: 'st-07', status: 'presente' },
      { studentId: 'st-08', status: 'presente' },
      { studentId: 'st-09', status: 'presente' },
      { studentId: 'st-10', status: 'ausente' },
      { studentId: 'st-11', status: 'presente' },
      { studentId: 'st-12', status: 'presente' },
      { studentId: 'st-13', status: 'presente' },
      { studentId: 'st-14', status: 'presente' },
      { studentId: 'st-15', status: 'presente' },
    ],
  },
];

export const INITIAL_GRADEBOOKS: Record<string, ClassGradeBook> = {
  'turma-eng301': {
    classId: 'turma-eng301',
    weights: { p1: 0.35, p2: 0.35, trabalho: 0.20, atividades: 0.10 },
    passingGrade: 7.0,
    recoveryGrade: 5.0,
    grades: [
      { studentId: 'st-01', p1: 8.5, p2: 9.0, trabalho: 9.5, atividades: 10.0, notes: 'Excelente projeto arquitetural' },
      { studentId: 'st-02', p1: 7.0, p2: 7.5, trabalho: 8.0, atividades: 8.5 },
      { studentId: 'st-03', p1: 9.8, p2: 10.0, trabalho: 9.8, atividades: 10.0, notes: 'Destaque acadêmico' },
      { studentId: 'st-04', p1: 4.5, p2: 5.2, trabalho: 6.0, atividades: 5.0, notes: 'Necessita reforço em modelagem' },
      { studentId: 'st-05', p1: 8.8, p2: 8.5, trabalho: 9.0, atividades: 9.0 },
      { studentId: 'st-06', p1: 6.8, p2: 7.2, trabalho: 7.5, atividades: 7.0 },
      { studentId: 'st-07', p1: 9.0, p2: 8.7, trabalho: 9.0, atividades: 9.5 },
      { studentId: 'st-08', p1: 5.5, p2: 6.0, trabalho: 7.0, atividades: 6.5 },
      { studentId: 'st-09', p1: 9.2, p2: 9.5, trabalho: 9.5, atividades: 10.0 },
      { studentId: 'st-10', p1: 4.0, p2: 4.5, trabalho: 5.5, atividades: 4.0, notes: 'Risco de reprovação' },
      { studentId: 'st-11', p1: 7.5, p2: 8.0, trabalho: 8.0, atividades: 8.5 },
      { studentId: 'st-12', p1: 8.2, p2: 8.8, trabalho: 8.5, atividades: 9.0 },
      { studentId: 'st-13', p1: 7.8, p2: 7.5, trabalho: 8.0, atividades: 8.0 },
      { studentId: 'st-14', p1: 8.0, p2: 8.2, trabalho: 8.5, atividades: 9.0 },
      { studentId: 'st-15', p1: 9.5, p2: 9.2, trabalho: 9.5, atividades: 9.5 },
    ],
  },
  'turma-alg202': {
    classId: 'turma-alg202',
    weights: { p1: 0.35, p2: 0.35, trabalho: 0.20, atividades: 0.10 },
    passingGrade: 7.0,
    recoveryGrade: 5.0,
    grades: [
      { studentId: 'st-21', p1: 8.0, p2: 8.5, trabalho: 9.0, atividades: 8.5 },
      { studentId: 'st-22', p1: 9.0, p2: 9.2, trabalho: 9.5, atividades: 10.0 },
      { studentId: 'st-23', p1: 6.5, p2: 7.0, trabalho: 7.5, atividades: 7.0 },
      { studentId: 'st-24', p1: 5.0, p2: 5.5, trabalho: 6.0, atividades: 5.5 },
      { studentId: 'st-25', p1: 7.8, p2: 8.0, trabalho: 8.5, atividades: 8.0 },
      { studentId: 'st-26', p1: 9.5, p2: 9.8, trabalho: 10.0, atividades: 10.0 },
      { studentId: 'st-27', p1: 7.2, p2: 7.5, trabalho: 8.0, atividades: 7.5 },
      { studentId: 'st-28', p1: 8.8, p2: 9.0, trabalho: 9.0, atividades: 9.5 },
      { studentId: 'st-29', p1: 6.0, p2: 6.5, trabalho: 7.0, atividades: 6.0 },
      { studentId: 'st-30', p1: 9.2, p2: 9.0, trabalho: 9.5, atividades: 9.5 },
    ],
  },
  'turma-bd401': {
    classId: 'turma-bd401',
    weights: { p1: 0.35, p2: 0.35, trabalho: 0.20, atividades: 0.10 },
    passingGrade: 7.0,
    recoveryGrade: 5.0,
    grades: [
      { studentId: 'st-31', p1: 8.0, p2: 8.2, trabalho: 8.5, atividades: 9.0 },
      { studentId: 'st-32', p1: 7.5, p2: 8.0, trabalho: 8.0, atividades: 8.5 },
      { studentId: 'st-33', p1: 6.8, p2: 7.2, trabalho: 7.5, atividades: 7.0 },
      { studentId: 'st-34', p1: 9.5, p2: 9.8, trabalho: 10.0, atividades: 10.0 },
      { studentId: 'st-35', p1: 5.5, p2: 6.0, trabalho: 6.5, atividades: 6.0 },
      { studentId: 'st-36', p1: 8.2, p2: 8.5, trabalho: 9.0, atividades: 8.5 },
      { studentId: 'st-37', p1: 9.0, p2: 9.2, trabalho: 9.5, atividades: 9.0 },
      { studentId: 'st-38', p1: 7.2, p2: 7.8, trabalho: 8.0, atividades: 8.0 },
    ],
  },
  'turma-ia501': {
    classId: 'turma-ia501',
    weights: { p1: 0.35, p2: 0.35, trabalho: 0.20, atividades: 0.10 },
    passingGrade: 7.0,
    recoveryGrade: 5.0,
    grades: [
      { studentId: 'st-41', p1: 10.0, p2: 9.8, trabalho: 10.0, atividades: 10.0 },
      { studentId: 'st-42', p1: 8.8, p2: 9.0, trabalho: 9.2, atividades: 9.0 },
      { studentId: 'st-43', p1: 8.5, p2: 8.8, trabalho: 9.0, atividades: 9.0 },
      { studentId: 'st-44', p1: 7.8, p2: 8.2, trabalho: 8.5, atividades: 8.0 },
      { studentId: 'st-45', p1: 9.2, p2: 9.5, trabalho: 9.8, atividades: 9.5 },
      { studentId: 'st-46', p1: 8.0, p2: 8.5, trabalho: 8.8, atividades: 8.5 },
    ],
  },
};

export const INITIAL_EVALUATIONS: ClassEvaluation[] = [
  {
    id: 'eval-01',
    classId: 'turma-eng301',
    date: '2026-08-15',
    academicPeriod: '2026/1 - 1º Bimestre',
    engagementRating: 4.5,
    disciplineRating: 4.8,
    homeworkDeliveryRating: 4.2,
    criticalThinkingRating: 4.6,
    qualitativeSummary: 'A turma demonstra grande proatividade em dinâmicas de desenvolvimento de software em equipe e interesse marcante por arquitetura de software moderna. Pontos de melhoria concentram-se na formalização da documentação de requisitos e na pontualidade das entregas individuais de 3 alunos específicos.',
    strengths: [
      'Domínio avançado de ferramentas de versionamento (Git) e integração contínua',
      'Excelente espírito colaborativo durante as sprints práticas',
      'Elevada média geral nas provas dissertativas (8.02)',
    ],
    attentionPoints: [
      'Dois estudantes com frequência próxima ao limite regulamentar de 75%',
      'Necessidade de reforçar testes unitários automatizados',
    ],
    pedagogicalActionPlan: '1. Promover oficina prática de TDD (Test-Driven Development) no início da próxima semana.\n2. Agendar atendimento pedagógico individual com Daniel Ramos e Igor Siqueira para acompanhamento de assiduidade.\n3. Implementar gamificação nas entregas de relatórios semanais.',
    aiGenerated: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Prazo Limite: Fechamento de Diários e Faltas (1º Bimestre)',
    content: 'Prezados docentes, lembramos que o prazo estipulado pelo Conselho Acadêmico para lançamento integral das faltas e notas do 1º Bimestre encerra-se impreterivelmente na próxima sexta-feira às 23:59.',
    sender: 'Coordenação Acadêmica de Graduação',
    category: 'urgente',
    date: '2026-08-19',
    isRead: false,
    type: 'received',
  },
  {
    id: 'notif-02',
    title: 'Convocação para Reunião Pedagógica Interdisciplinar',
    content: 'Convidamos todos os professores do DCTI para a reunião semestral de alinhamento pedagógico e avaliação de projetos integradores, que ocorrerá no Auditório Nobre na próxima quinta-feira às 14:00.',
    sender: 'Diretoria de Ensino',
    category: 'institucional',
    date: '2026-08-17',
    isRead: true,
    type: 'received',
  },
  {
    id: 'notif-03',
    title: 'Aviso sobre Entrega do Projeto de Clean Architecture',
    content: 'Olá pessoal da turma de Engenharia de Software! O repositório no GitHub Classroom para a submissão do trabalho da Sprint 2 já está liberado. Lembrem-se de incluir o diagrama de pacotes no README.',
    sender: 'Prof. Dr. Marcelo Carvalho Silveira',
    targetClassId: 'turma-eng301',
    category: 'material',
    date: '2026-08-18',
    isRead: true,
    type: 'sent',
    readByCount: 14,
    totalTargetCount: 15,
  },
  {
    id: 'notif-04',
    title: 'Gabarito e Comentários da Avaliação P1 Disponíveis',
    content: 'As notas e a resolução detalhada da Prova P1 já foram inseridas no Portal. Dúvidas sobre a correção serão atendidas durante o horário de gabinete de amanhã.',
    sender: 'Prof. Dr. Marcelo Carvalho Silveira',
    targetClassId: 'turma-alg202',
    category: 'prova',
    date: '2026-08-16',
    isRead: true,
    type: 'sent',
    readByCount: 10,
    totalTargetCount: 10,
  },
];

export const INITIAL_AVAILABILITY_SUBMISSION: TeacherAvailabilitySubmission = {
  id: 'avail-2026-2',
  submissionDate: '2026-08-10',
  semester: '2026/2 (Próximo Semestre)',
  status: 'Aprovado',
  maxClassesPerDay: 4,
  preferredDaysOff: ['Quarta-feira (Manhã)'],
  allowConsecutiveClasses: true,
  preferredModality: 'Presencial',
  healthOrTravelRestrictions: 'Preferência por alocar aulas noturnas nas terças e quintas para conciliar com grupo de pesquisa na USP às quartas à tarde.',
  justifications: 'Dedicação exclusiva para coordenação do Laboratório de Inovação nas terças à tarde.',
  grid: {
    'seg-m1': 'disponivel',
    'seg-m2': 'disponivel',
    'seg-t1': 'disponivel',
    'seg-t2': 'disponivel',
    'seg-n1': 'preferencial',
    'seg-n2': 'preferencial',
    'ter-m1': 'disponivel',
    'ter-m2': 'disponivel',
    'ter-t1': 'indisponivel',
    'ter-t2': 'indisponivel',
    'ter-n1': 'preferencial',
    'ter-n2': 'preferencial',
    'qua-m1': 'disponivel',
    'qua-m2': 'disponivel',
    'qua-t1': 'indisponivel',
    'qua-t2': 'indisponivel',
    'qua-n1': 'disponivel',
    'qua-n2': 'disponivel',
    'qui-m1': 'disponivel',
    'qui-m2': 'disponivel',
    'qui-t1': 'disponivel',
    'qui-t2': 'disponivel',
    'qui-n1': 'preferencial',
    'qui-n2': 'preferencial',
    'sex-m1': 'disponivel',
    'sex-m2': 'disponivel',
    'sex-t1': 'preferencial',
    'sex-t2': 'preferencial',
    'sex-n1': 'indisponivel',
    'sex-n2': 'indisponivel',
    'sab-m1': 'indisponivel',
    'sab-m2': 'indisponivel',
  },
};

export const INITIAL_MATERIALS: ClassMaterial[] = [
  {
    id: 'mat-01',
    classId: 'turma-eng301',
    title: 'Slides da Aula 04: Padrões de Projeto GoF (Criacionais)',
    description: 'Apresentação completa detalhando Factory Method, Abstract Factory, Singleton e Builder com exemplos em TypeScript e Java.',
    type: 'slide',
    category: 'Unidade 2 - Padrões de Arquitetura',
    fileSize: '4.8 MB',
    fileUrl: '#',
    uploadDate: '2026-08-14',
    isPublished: true,
    downloadsCount: 15,
  },
  {
    id: 'mat-02',
    classId: 'turma-eng301',
    title: 'Lista de Exercícios Práticos: Refatoração para Clean Architecture',
    description: 'Estudo de caso de um sistema de comércio eletrônico legado para refatoração em camadas desacopladas.',
    type: 'exercicio',
    category: 'Unidade 2 - Padrões de Arquitetura',
    fileSize: '1.2 MB',
    fileUrl: '#',
    uploadDate: '2026-08-16',
    isPublished: true,
    downloadsCount: 13,
  },
  {
    id: 'mat-03',
    classId: 'turma-eng301',
    title: 'Repositório Template de Código (GitHub)',
    description: 'Boilerplate com Node.js, TypeScript, Vitest e Docker configurados para o Trabalho Semestral.',
    type: 'codigo',
    category: 'Trabalho Semestral',
    externalLink: 'https://github.com/universidade-dcti/clean-arch-boilerplate',
    uploadDate: '2026-08-10',
    isPublished: true,
    downloadsCount: 15,
  },
  {
    id: 'mat-04',
    classId: 'turma-alg202',
    title: 'Apostila Completa: Árvores Binárias de Busca e Balanceamento AVL',
    description: 'Material didático autoral com demonstração passo a passo de rotações simples e duplas.',
    type: 'pdf',
    category: 'Módulo 3 - Estruturas de Dados Avançadas',
    fileSize: '6.4 MB',
    fileUrl: '#',
    uploadDate: '2026-08-08',
    isPublished: true,
    downloadsCount: 10,
  },
  {
    id: 'mat-05',
    classId: 'turma-ia501',
    title: 'Jupyter Notebook: Implementação de Redes Convolucionais com PyTorch',
    description: 'Guia interativo com código executável para classificação de imagens médicas.',
    type: 'codigo',
    category: 'Unidade 3 - Deep Learning',
    fileSize: '8.2 MB',
    fileUrl: '#',
    uploadDate: '2026-08-12',
    isPublished: true,
    downloadsCount: 6,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // Segunda-feira (Day 1)
  { id: 'tt-seg-1', dayOfWeek: 1, dayName: 'Segunda-feira', startTime: '07:30', endTime: '09:10', periodName: 'Matutino', slotIndex: 1, classId: 'turma-alg202', className: 'Algoritmos e Estruturas II', classCode: 'ALG-202', room: 'Sala 204 - Bloco Central', color: '#10b981' },
  { id: 'tt-seg-2', dayOfWeek: 1, dayName: 'Segunda-feira', startTime: '09:30', endTime: '11:10', periodName: 'Matutino', slotIndex: 2 },
  { id: 'tt-seg-3', dayOfWeek: 1, dayName: 'Segunda-feira', startTime: '18:50', endTime: '20:30', periodName: 'Noturno', slotIndex: 1 },
  
  // Terça-feira (Day 2)
  { id: 'tt-ter-1', dayOfWeek: 2, dayName: 'Terça-feira', startTime: '18:50', endTime: '20:30', periodName: 'Noturno', slotIndex: 1, classId: 'turma-eng301', className: 'Engenharia de Software', classCode: 'ENG-301', room: 'Lab 402 - Bloco B', color: '#3b82f6' },
  { id: 'tt-ter-2', dayOfWeek: 2, dayName: 'Terça-feira', startTime: '20:45', endTime: '22:25', periodName: 'Noturno', slotIndex: 2 },

  // Quarta-feira (Day 3)
  { id: 'tt-qua-1', dayOfWeek: 3, dayName: 'Quarta-feira', startTime: '07:30', endTime: '09:10', periodName: 'Matutino', slotIndex: 1, classId: 'turma-alg202', className: 'Algoritmos e Estruturas II', classCode: 'ALG-202', room: 'Sala 204 - Bloco Central', color: '#10b981' },
  { id: 'tt-qua-2', dayOfWeek: 3, dayName: 'Quarta-feira', startTime: '20:45', endTime: '22:25', periodName: 'Noturno', slotIndex: 2, classId: 'turma-bd401', className: 'Banco de Dados Avançado', classCode: 'BD-401', room: 'Lab 201 - Bloco A', color: '#8b5cf6' },

  // Quinta-feira (Day 4)
  { id: 'tt-qui-1', dayOfWeek: 4, dayName: 'Quinta-feira', startTime: '18:50', endTime: '20:30', periodName: 'Noturno', slotIndex: 1, classId: 'turma-eng301', className: 'Engenharia de Software', classCode: 'ENG-301', room: 'Lab 402 - Bloco B', color: '#3b82f6' },
  { id: 'tt-qui-2', dayOfWeek: 4, dayName: 'Quinta-feira', startTime: '20:45', endTime: '22:25', periodName: 'Noturno', slotIndex: 2 },

  // Sexta-feira (Day 5)
  { id: 'tt-sex-1', dayOfWeek: 5, dayName: 'Sexta-feira', startTime: '13:30', endTime: '15:10', periodName: 'Vespertino', slotIndex: 1, classId: 'turma-ia501', className: 'Inteligência Artificial', classCode: 'IA-501', room: 'Auditório 3 - Pós', color: '#f59e0b' },
  { id: 'tt-sex-2', dayOfWeek: 5, dayName: 'Sexta-feira', startTime: '15:30', endTime: '17:10', periodName: 'Vespertino', slotIndex: 2, classId: 'turma-ia501', className: 'Inteligência Artificial (Prática)', classCode: 'IA-501', room: 'Auditório 3 - Pós', color: '#f59e0b' },
  { id: 'tt-sex-3', dayOfWeek: 5, dayName: 'Sexta-feira', startTime: '18:50', endTime: '20:30', periodName: 'Noturno', slotIndex: 1, classId: 'turma-bd401', className: 'Banco de Dados Avançado', classCode: 'BD-401', room: 'Lab 201 - Bloco A', color: '#8b5cf6' },
];

export const INITIAL_CALENDAR_EVENTS: AcademicCalendarEvent[] = [
  {
    id: 'cal-01',
    title: 'Início do Semestre Letivo 2026/1',
    description: 'Acolhimento aos calouros e início das aulas regulares em todos os cursos de graduação.',
    startDate: '2026-08-03',
    category: 'academico',
    isImportant: true,
  },
  {
    id: 'cal-02',
    title: 'Prazo Limite: Ajuste de Matrículas e Inclusão de Disciplinas',
    description: 'Último dia para alunos solicitarem dispensa, equivalência ou inclusão de matérias.',
    startDate: '2026-08-21',
    category: 'academico',
    isImportant: false,
  },
  {
    id: 'cal-03',
    title: 'Feriado Nacional: Independência do Brasil',
    description: 'Sem atividades acadêmicas ou administrativas.',
    startDate: '2026-09-07',
    category: 'feriado',
    isImportant: false,
  },
  {
    id: 'cal-04',
    title: 'Semana de Avaliações Parciais (P1)',
    description: 'Período oficial reservado para aplicação das primeiras provas regimentais do semestre.',
    startDate: '2026-09-21',
    endDate: '2026-09-26',
    category: 'provas',
    isImportant: true,
  },
  {
    id: 'cal-05',
    title: 'Data Limite para Digitação de Notas da P1',
    description: 'Fechamento do sistema acadêmico para inserção das notas e frequência do 1º Bimestre.',
    startDate: '2026-10-02',
    category: 'notas',
    isImportant: true,
  },
  {
    id: 'cal-06',
    title: 'Feriado: Nossa Senhora Aparecida / Dia das Crianças',
    description: 'Recesso acadêmico.',
    startDate: '2026-10-12',
    category: 'feriado',
    isImportant: false,
  },
  {
    id: 'cal-07',
    title: 'Dia do Professor (Recesso Escolar)',
    description: 'Homenagem ao corpo docente. Sem aulas.',
    startDate: '2026-10-15',
    category: 'recesso',
    isImportant: true,
  },
  {
    id: 'cal-08',
    title: 'Semana Acadêmica de Tecnologia e Engenharia (SATEC 2026)',
    description: 'Ciclo de palestras, minicursos, hackathons e mostra de projetos de iniciação científica.',
    startDate: '2026-10-19',
    endDate: '2026-10-23',
    category: 'academico',
    isImportant: true,
  },
  {
    id: 'cal-09',
    title: 'Semana de Avaliações Finais (P2)',
    description: 'Aplicação das provas do 2º Bimestre e avaliação dos projetos interdisciplinares.',
    startDate: '2026-11-23',
    endDate: '2026-11-28',
    category: 'provas',
    isImportant: true,
  },
  {
    id: 'cal-10',
    title: 'Prazo Final: Lançamento de Notas Finais e Frequência',
    description: 'Encerramento oficial do diário eletrônico para apuração de estudantes em exame final.',
    startDate: '2026-12-04',
    category: 'notas',
    isImportant: true,
  },
  {
    id: 'cal-11',
    title: 'Período de Exames Finais e Provas de Recuperação',
    description: 'Aplicação de exames para discentes com média entre 5.0 e 6.9.',
    startDate: '2026-12-07',
    endDate: '2026-12-11',
    category: 'provas',
    isImportant: true,
  },
  {
    id: 'cal-12',
    title: 'Conselho de Classe e Reunião de Encerramento do Semestre',
    description: 'Deliberação final dos colegiados de curso e homologação dos resultados.',
    startDate: '2026-12-15',
    category: 'reuniao',
    isImportant: true,
  },
  {
    id: 'cal-13',
    title: 'Início das Férias Docentes',
    description: 'Período de recesso e férias regulamentares do corpo docente.',
    startDate: '2026-12-18',
    endDate: '2027-01-20',
    category: 'recesso',
    isImportant: true,
  },
];
